default_db_uri: "postgresql+psycopg://postgres:postgres@localhost:5432/hapirestore"

dataset:
  title: "HDX HAPI data"
  name: "hdx-hapi-"

subcategories:
  idps:
    tags:
      - "displacement"
      - "internally displaced persons-idp"
      - "migration"
    resource:
      name: "IDPs Data"
      description: "IDPs data from HDX HAPI, please see [the documentation](https://hdx-hapi.readthedocs.io/en/latest/data_usage_guides/affected_people/#internally-displaced-persons) for more information  \n Source: [International Organization for Migration (IOM)](https://data.humdata.org/organization/f53d32cd-132c-4ef4-bc6d-058f94d08adf?)  \n License: Copyright © International Organization for Migration 2018 IOM reserves the right to assert ownership of the Materials collected on the https://data.humdata.org/ website. The Materials may be viewed, downloaded, and printed for non-commercial use only, without, inter alia, any right to sell, resell, redistribute or create derivative works therefrom. At all times the User shall credit the DTM as the source, unless otherwise stated. The user must include the URL of the Materials from the HDX Website, as well as the following credit line: Source: \"International Organization for Migration (IOM), Displacement Tracking Matrix (DTM)\"."
      filename: "hdx_hapi_idps"
    hxltags:
      location_code: "#country+code"
      has_hrp: "#meta+has_hrp"
      in_gho: "#meta+in_gho"
      provider_admin1_name: "#adm1+name+provider"
      provider_admin2_name: "#adm2+name+provider"
      admin1_code: "#adm1+code"
      admin1_name: "#adm1+name"
      admin2_code: "#adm2+code"
      admin2_name: "#adm2+name"
      operation: "#operation+name"
      assessment_type: "#assessment+type"
      population: "#affected+idps"
      reporting_round: "#round+code"
      reference_period_start: "#date+start"
      reference_period_end: "#date+end"

  refugees:
    tags:
      - "refugees"
    resource:
      name: "Refugees Data"
      description: "Refugees and Persons of Concern data from HDX HAPI, please see [the documentation](https://hdx-hapi.readthedocs.io/en/latest/data_usage_guides/affected_people/#refugees-persons-of-concern) for more information  \n Source: [UNHCR](https://data.humdata.org/organization/unhcr)  \n License: [Creative Commons Attribution for Intergovernmental Organisations](https://data.humdata.org/faqs/licenses)"
      filename: "hdx_hapi_refugees"
    hxltags:
      origin_location_code: "#country+code+origin"
      origin_has_hrp: "#meta+has_hrp+origin"
      origin_in_gho: "#meta+in_gho+origin"
      asylum_location_code: "#country+code+asylum"
      asylum_has_hrp: "#meta+has_hrp+asylum"
      asylum_in_gho: "#meta+in_gho+asylum"
      population_group: "#population_group+code"
      gender: "#gender+code"
      age_range: "#age+range"
      min_age: "#age+min"
      max_age: "#age+max"
      population: "#population"
      reference_period_start: "#date+start"
      reference_period_end: "#date+end"

  returnees:
    tags:
      - "returnees"
    resource:
      name: "Returnees Data"
      description: "Returnees data from HDX HAPI, please see [the documentation](https://hdx-hapi.readthedocs.io/en/latest/data_usage_guides/affected_people/#returnees) for more information  \n Source: [UNHCR](https://data.humdata.org/organization/unhcr)  \n License: [Creative Commons Attribution for Intergovernmental Organisations](https://data.humdata.org/faqs/licenses)"
      filename: "hdx_hapi_returnees"
    hxltags:
      origin_location_code: "#country+code+origin"
      origin_has_hrp: "#meta+has_hrp+origin"
      origin_in_gho: "#meta+in_gho+origin"
      asylum_location_code: "#country+code+asylum"
      asylum_has_hrp: "#meta+has_hrp+asylum"
      asylum_in_gho: "#meta+in_gho+asylum"
      population_group: "#population_group+code"
      gender: "#gender+code"
      age_range: "#age+range"
      min_age: "#age+min"
      max_age: "#age+max"
      population: "#population"
      reference_period_start: "#date+start"
      reference_period_end: "#date+end"

  humanitarian_needs:
    tags:
      - "humanitarian needs overview-hno"
      - "people in need-pin"
    resource:
      name: "Humanitarian Needs Data"
      description: "Humanitarian needs data from HDX HAPI, please see [the documentation](https://hdx-hapi.readthedocs.io/en/latest/data_usage_guides/affected_people/#humanitarian-needs) for more information  \n Source: [OCHA HPC Tools](https://data.humdata.org/organization/49f12a06-1605-4f98-89f1-eaec37a0fdfe)  \n License: [Creative Commons Attribution for Intergovernmental Organisations](https://data.humdata.org/faqs/licenses)"
      filename: "hdx_hapi_humanitarian_needs"
    hxltags:
      location_code: "#country+code"
      has_hrp: "#meta+has_hrp"
      in_gho: "#meta+in_gho"
      provider_admin1_name: "#adm1+name+provider"
      provider_admin2_name: "#adm2+name+provider"
      admin1_code: "#adm1+code"
      admin1_name: "#adm1+name"
      admin2_code: "#adm2+code"
      admin2_name: "#adm2+name"
      sector_code: "#sector+cluster+code"
      sector_name: "#sector+cluster+name"
      category: "#category"
      population_status: "#population+status"
      population: "#population"
      reference_period_start: "#date+start"
      reference_period_end: "#date+end"

  operational_presence:
    tags:
      - "operational presence"
      - "who is doing what and where-3w-4w-5w"
    resource:
      name: "Operational Presence Data"
      description: "Who is doing What Where - Operational Presence data from HDX HAPI, please see [the documentation](https://hdx-hapi.readthedocs.io/en/latest/data_usage_guides/coordination_and_context/#who-is-doing-what-where-operational-presence) for more information  \n Source: [OCHA Lebanon](https://data.humdata.org/organization/a5d3183c-aa19-4320-be20-afb8eeb23ba9)  \n License: [Creative Commons Attribution for Intergovernmental Organisations](https://data.humdata.org/faqs/licenses)"
      filename: "hdx_hapi_operational_presence"
    hxltags:
      location_code: "#country+code"
      has_hrp: "#meta+has_hrp"
      in_gho: "#meta+in_gho"
      provider_admin1_name: "#adm1+name+provider"
      provider_admin2_name: "#adm2+name+provider"
      admin1_code: "#adm1+code"
      admin1_name: "#adm1+name"
      admin2_code: "#adm2+code"
      admin2_name: "#adm2+name"
      org_acronym: "#org+acronym"
      org_name: "#org+name"
      org_type_description: "#org+type"
      sector_code: "#sector+cluster+code"
      sector_name: "#sector+cluster+name"
      reference_period_start: "#date+start"
      reference_period_end: "#date+end"

  funding:
    tags:
      - "funding"
    resource:
      name: "Funding Data"
      description: "Funding data from HDX HAPI, please see [the documentation](https://hdx-hapi.readthedocs.io/en/latest/data_usage_guides/coordination_and_context/#funding) for more information  \n Source: [OCHA Financial Tracking System (FTS)](https://data.humdata.org/organization/fb7c2910-6080-4b66-8b4f-0be9b6dc4d8e)  \n License: [Creative Commons Attribution for Intergovernmental Organisations](https://data.humdata.org/faqs/licenses)"
      filename: "hdx_hapi_funding"
    hxltags:
      location_code: "#country+code"
      has_hrp: "#meta+has_hrp"
      in_gho: "#meta+in_gho"
      appeal_code: "#activity+appeal+id+external"
      appeal_name: "#activity+appeal+name"
      appeal_type: "#activity+appeal+type+name"
      requirements_usd: "#value+funding+required+usd"
      funding_usd: "#value+funding+total+usd"
      funding_pct: "#value+funding+pct"
      reference_period_start: "#date+start"
      reference_period_end: "#date+end"

  conflict_event:
    tags:
      - "conflict-violence"
    resource:
      name: "Conflict Event Data"
      description: "Conflict Event data from HDX HAPI, please see [the documentation](https://hdx-hapi.readthedocs.io/en/latest/data_usage_guides/coordination_and_context/#conflict-events) for more information  \n Source: [Armed Conflict Location & Event Data Project (ACLED)](https://data.humdata.org/organization/b67e6c74-c185-4f43-b561-0e114a736f19)  \n License: By using ACLED data you agree to abide by the [Terms of Use and Attribution Policy](https://acleddata.com/terms-of-use/)."
      filename: "hdx_hapi_conflict_event"
    hxltags:
      location_code: "#country+code"
      has_hrp: "#meta+has_hrp"
      in_gho: "#meta+in_gho"
      provider_admin1_name: "#adm1+name+provider"
      provider_admin2_name: "#adm2+name+provider"
      admin1_code: "#adm1+code"
      admin1_name: "#adm1+name"
      admin2_code: "#adm2+code"
      admin2_name: "#adm2+name"
      event_type: "#event+type"
      events: "#indicator+event+num"
      fatalities: "#affected+killed"
      reference_period_start: "#date+start"
      reference_period_end: "#date+end"

  national_risk:
    tags:
      - "hazards and risk"
    resource:
      name: "National Risk Data"
      description: "National Risk data from HDX HAPI, please see [the documentation](https://hdx-hapi.readthedocs.io/en/latest/data_usage_guides/coordination_and_context/#national-risk) for more information  \n Source: [INFORM](https://data.humdata.org/organization/e116c55a-d536-4b47-9308-94b1c7457afe)  \n License: [Creative Commons Attribution International](https://data.humdata.org/faqs/licenses)"
      filename: "hdx_hapi_national_risk"
    hxltags:
      location_code: "#country+code"
      has_hrp: "#meta+has_hrp"
      in_gho: "#meta+in_gho"
      risk_class: "#risk+class"
      global_rank: "#risk+rank"
      overall_risk: "#risk+total"
      hazard_exposure_risk: "#risk+hazard"
      vulnerability_risk: "#risk+vulnerability"
      coping_capacity_risk: "#risk+coping+capacity"
      meta_missing_indicators_pct: "#meta+missing+indicators+pct"
      meta_avg_recentness_years: "#meta+recentness+avg"
      reference_period_start: "#date+start"
      reference_period_end: "#date+end"

  food_security:
    tags:
      - "food security"
    resource:
      name: "Food Security Data"
      description: "Food Security data from HDX HAPI, please see [the documentation](https://hdx-hapi.readthedocs.io/en/latest/data_usage_guides/food_security_and_nutrition/#food-security) for more information  \n Source: [Integrated Food Security Phase Classification (IPC)](https://data.humdata.org/organization/da501ffc-aadb-43f5-9d28-8fa572fd9ce0)  \n License: [Public Domain / No Restrictions](https://data.humdata.org/faqs/licenses)"
      filename: "hdx_hapi_food_security"
    hxltags:
      location_code: "#country+code"
      has_hrp: "#meta+has_hrp"
      in_gho: "#meta+in_gho"
      provider_admin1_name: "#adm1+name+provider"
      provider_admin2_name: "#adm2+name+provider"
      admin1_code: "#adm1+code"
      admin1_name: "#adm1+name"
      admin2_code: "#adm2+code"
      admin2_name: "#adm2+name"
      ipc_phase: "#severity+v_ipc"
      ipc_type: "#period+v_ipc"
      population_in_phase: "#affected+num"
      population_fraction_in_phase: "#affected+pct"
      reference_period_start: "#date+start"
      reference_period_end: "#date+end"

  food_price:
    tags:
      - "economics"
      - "markets"
      - "food security"
    resource:
      name: "Food Price Data"
      description: "Food Prices data from HDX HAPI, please see [the documentation](https://hdx-hapi.readthedocs.io/en/latest/data_usage_guides/food_security_and_nutrition/#food-prices) for more information  \n Source: [WFP - World Food Programme](https://data.humdata.org/organization/3ecac442-7fed-448d-8f78-b385ef6f84e7)  \n License: [Creative Commons Attribution for Intergovernmental Organisations](https://data.humdata.org/faqs/licenses)"
      filename: "hdx_hapi_food_price"
    hxltags:
      location_code: "#country+code"
      has_hrp: "#meta+has_hrp"
      in_gho: "#meta+in_gho"
      provider_admin1_name: "#adm1+name+provider"
      provider_admin2_name: "#adm2+name+provider"
      admin1_code: "#adm1+code"
      admin1_name: "#adm1+name"
      admin2_code: "#adm2+code"
      admin2_name: "#adm2+name"
      market_name: "#loc+market+name"
      lat: "#geo+lat"
      lon: "#geo+lon"
      commodity_category: "#item+type"
      commodity_name: "#item+name"
      unit: "#item+unit"
      price_flag: "#item+price+flag"
      price_type: "#item+price+type"
      currency_code: "#currency"
      price: "#value"
      reference_period_start: "#date+start"
      reference_period_end: "#date+end"

  population:
    tags:
      - "baseline population"
    resource:
      name: "Population Data"
      description: TODO
      filename: "hdx_hapi_population"
    hxltags:
      location_code: "#country+code"
      has_hrp: "#meta+has_hrp"
      in_gho: "#meta+in_gho"
      provider_admin1_name: "#adm1+name+provider"
      provider_admin2_name: "#adm2+name+provider"
      admin1_code: "#adm1+code"
      admin1_name: "#adm1+name"
      admin2_code: "#adm2+code"
      admin2_name: "#adm2+name"
      gender: "#gender+code"
      age_range: "#age+range"
      min_age: "#age+min"
      max_age: "#age+max"
      population: "#population"
      reference_period_start: "#date+start"
      reference_period_end: "#date+end"

  poverty_rate:
    tags:
      - "education"
      - "health"
      - "indicators"
      - "poverty"
    resource:
      name: "Poverty Rate Data"
      description: "Poverty Rate data from HDX HAPI, please see [the documentation](https://hdx-hapi.readthedocs.io/en/latest/data_usage_guides/population_and_socio-economy/#poverty-rate)  \n Source: [Oxford Poverty & Human Development Initiative](https://data.humdata.org/organization/00547685-9ded-4d69-9ca5-47d5278ead7c)  \n License: [Public Domain / No Restrictions](https://data.humdata.org/faqs/licenses)"
      filename: "hdx_hapi_poverty_rate"
    hxltags:
      location_code: "#country+code"
      has_hrp: "#meta+has_hrp"
      in_gho: "#meta+in_gho"
      provider_admin1_name: "#adm1+name+provider"
      admin1_code: "#adm1+code"
      admin1_name: "#adm1+name"
      mpi: "#indicator+mpi"
      headcount_ratio: "#indicator+headcount_ratio"
      intensity_of_deprivation: "#indicator+intensity_of_deprivation"
      vulnerable_to_poverty: "#indicator+vulnerable_to_poverty"
      in_severe_poverty: "#indicator+in_severe_poverty"
      reference_period_start: "#date+start"
      reference_period_end: "#date+end"

  data_availability:
    tags: []
    resource:
      name: "Data Availability Data"
      description: "Data Availability Data"
      filename: "hdx_hapi_data_availability"
    hxltags:
      category: "#category"
      subcategory: "#subcategory"
      location_code: "#country+code"
      admin1_code: "#adm1+code"
      admin1_name: "#adm1+name"
      admin2_code: "#adm2+code"
      admin2_name: "#adm2+name"
