default_db_uri: "postgresql+psycopg://postgres:postgres@localhost:5432/hapirestore"

country_dataset_title: "HDX HAPI Data for {suffix}"
dataset_name: "hdx-hapi-{suffix}"
default_source: "HDX HAPI"
default_license: "cc-by-igo"
country_multiple_licenses: "Multiple licenses, please see individual resources for specific license information"

subcategories:
  idps:
    make_global_dataset: False
    title: "HDX HAPI - Affected People: Internally-Displaced Persons"
    tags:
      - "displacement"
      - "internally displaced persons-idp"
      - "migration"
    resource:
      name: "Affected People: Internally-Displaced Persons"
      description: "IDPs data from HDX HAPI, please see [the documentation](https://hdx-hapi.readthedocs.io/en/latest/data_usage_guides/affected_people/#internally-displaced-persons) for more information"
      filename: "hdx_hapi_idps"
      p_coded: True
    headers:
      - location_code
      - has_hrp
      - in_gho
      - provider_admin1_name
      - provider_admin2_name
      - admin1_code
      - admin1_name
      - admin2_code
      - admin2_name
      - admin_level
      - operation
      - assessment_type
      - population
      - reporting_round
      - reference_period_start
      - reference_period_end

  refugees:
    make_global_dataset: False
    title: "HDX HAPI - Affected People: Refugees & Persons of Concern"
    tags:
      - "refugees"
    resource:
      name: "Affected People: Refugees & Persons of Concern"
      description: "Refugees and Persons of Concern data from HDX HAPI, please see [the documentation](https://hdx-hapi.readthedocs.io/en/latest/data_usage_guides/affected_people/#refugees-persons-of-concern) for more information"
      filename: "hdx_hapi_refugees"
    headers:
      - origin_location_code
      - origin_has_hrp
      - origin_in_gho
      - asylum_location_code
      - asylum_has_hrp
      - asylum_in_gho
      - population_group
      - gender
      - age_range
      - min_age
      - max_age
      - population
      - reference_period_start
      - reference_period_end

  returnees:
    make_global_dataset: False
    title: "HDX HAPI - Affected People: Returnees"
    tags:
      - "returnees"
    resource:
      name: "Affected People: Returnees"
      description: "Returnees data from HDX HAPI, please see [the documentation](https://hdx-hapi.readthedocs.io/en/latest/data_usage_guides/affected_people/#returnees) for more information"
      filename: "hdx_hapi_returnees"
    headers:
      - origin_location_code
      - origin_has_hrp
      - origin_in_gho
      - asylum_location_code
      - asylum_has_hrp
      - asylum_in_gho
      - population_group
      - gender
      - age_range
      - min_age
      - max_age
      - population
      - reference_period_start
      - reference_period_end

  humanitarian_needs:
    make_global_dataset: False
    title: "HDX HAPI - Affected People: Humanitarian Needs"
    tags:
      - "humanitarian needs overview-hno"
      - "people in need-pin"
    resource:
      name: "Affected People: Humanitarian Needs"
      description: "Humanitarian needs data from HDX HAPI, please see [the documentation](https://hdx-hapi.readthedocs.io/en/latest/data_usage_guides/affected_people/#humanitarian-needs) for more information"
      filename: "hdx_hapi_humanitarian_needs"
      p_coded: True
    headers:
      - location_code
      - has_hrp
      - in_gho
      - provider_admin1_name
      - provider_admin2_name
      - admin1_code
      - admin1_name
      - admin2_code
      - admin2_name
      - admin_level
      - sector_code
      - sector_name
      - category
      - population_status
      - population
      - reference_period_start
      - reference_period_end

  operational_presence:
    make_global_dataset: False
    title: "HDX HAPI - Coordination & Context: Operational Presence"
    tags:
      - "operational presence"
      - "who is doing what and where-3w-4w-5w"
    resource:
      name: "Coordination & Context: Operational Presence"
      description: "Operational Presence data from HDX HAPI, please see [the documentation](https://hdx-hapi.readthedocs.io/en/latest/data_usage_guides/coordination_and_context/#operational-presence) for more information"
      filename: "hdx_hapi_operational_presence"
      p_coded: True
    headers:
      - location_code
      - has_hrp
      - in_gho
      - provider_admin1_name
      - provider_admin2_name
      - admin1_code
      - admin1_name
      - admin2_code
      - admin2_name
      - admin_level
      - org_acronym
      - org_name
      - org_type_description
      - sector_code
      - sector_name
      - reference_period_start
      - reference_period_end

  funding:
    make_global_dataset: False
    title: "HDX HAPI - Coordination & Context: Funding"
    tags:
      - "funding"
    resource:
      name: "Coordination & Context: Funding"
      description: "Funding data from HDX HAPI, please see [the documentation](https://hdx-hapi.readthedocs.io/en/latest/data_usage_guides/coordination_and_context/#funding) for more information"
      filename: "hdx_hapi_funding"
    headers:
      - location_code
      - has_hrp
      - in_gho
      - appeal_code
      - appeal_name
      - appeal_type
      - requirements_usd
      - funding_usd
      - funding_pct
      - reference_period_start
      - reference_period_end

  conflict_event:
    make_global_dataset: False
    title: "HDX HAPI - Coordination & Context: Conflict Events"
    tags:
      - "conflict-violence"
    resource:
      name: "Coordination & Context: Conflict Events"
      description: "Conflict Event data from HDX HAPI, please see [the documentation](https://hdx-hapi.readthedocs.io/en/latest/data_usage_guides/coordination_and_context/#conflict-events) for more information"
      filename: "hdx_hapi_conflict_event"
      p_coded: True
    headers:
      - location_code
      - has_hrp
      - in_gho
      - provider_admin1_name
      - provider_admin2_name
      - admin1_code
      - admin1_name
      - admin2_code
      - admin2_name
      - admin_level
      - event_type
      - events
      - fatalities
      - reference_period_start
      - reference_period_end

  national_risk:
    make_global_dataset: True
    title: "HDX HAPI - Coordination & Context: National Risk"
    tags:
      - "hazards and risk"
    resource:
      name: "Coordination & Context: National Risk"
      description: "National Risk data from HDX HAPI, please see [the documentation](https://hdx-hapi.readthedocs.io/en/latest/data_usage_guides/coordination_and_context/#national-risk) for more information"
      filename: "hdx_hapi_national_risk"
    headers:
      - location_code
      - has_hrp
      - in_gho
      - risk_class
      - global_rank
      - overall_risk
      - hazard_exposure_risk
      - vulnerability_risk
      - coping_capacity_risk
      - meta_missing_indicators_pct
      - meta_avg_recentness_years
      - reference_period_start
      - reference_period_end

  food_security:
    make_global_dataset: False
    title: "HDX HAPI - Food Security, Nutrition & Poverty: Food Security"
    tags:
      - "food security"
    resource:
      name: "Food Security, Nutrition & Poverty: Food Security"
      description: "Food Security data from HDX HAPI, please see [the documentation](https://hdx-hapi.readthedocs.io/en/latest/data_usage_guides/food_security_nutrition_and_poverty/#food-security) for more information"
      filename: "hdx_hapi_food_security"
      p_coded: True
    headers:
      - location_code
      - has_hrp
      - in_gho
      - provider_admin1_name
      - provider_admin2_name
      - admin1_code
      - admin1_name
      - admin2_code
      - admin2_name
      - admin_level
      - ipc_phase
      - ipc_type
      - population_in_phase
      - population_fraction_in_phase
      - reference_period_start
      - reference_period_end

  food_price:
    make_global_dataset: False
    title: "HDX HAPI - Food Security, Nutrition & Poverty: Food Prices & Market Monitor"
    tags:
      - "economics"
      - "markets"
      - "food security"
    resource:
      name: "Food Security, Nutrition & Poverty: Food Prices & Market Monitor"
      description: "Food Prices & Market Monitor data from HDX HAPI, please see [the documentation](https://hdx-hapi.readthedocs.io/en/latest/data_usage_guides/food_security_nutrition_and_poverty/#food-prices-market-monitor) for more information"
      filename: "hdx_hapi_food_price"
      p_coded: True
    headers:
      - location_code
      - has_hrp
      - in_gho
      - provider_admin1_name
      - provider_admin2_name
      - admin1_code
      - admin1_name
      - admin2_code
      - admin2_name
      - admin_level
      - market_name
      - lat
      - lon
      - commodity_category
      - commodity_name
      - unit
      - price_flag
      - price_type
      - currency_code
      - price
      - reference_period_start
      - reference_period_end

  poverty_rate:
    make_global_dataset: False
    title: "HDX HAPI - Food Security, Nutrition & Poverty: Poverty Rate"
    tags:
      - "education"
      - "health"
      - "indicators"
      - "poverty"
    resource:
      name: "Food Security, Nutrition & Poverty: Poverty Rate"
      description: "Poverty Rate data from HDX HAPI, please see [the documentation](https://hdx-hapi.readthedocs.io/en/latest/data_usage_guides/food_security_nutrition_and_poverty/#poverty-rate) for more information"
      filename: "hdx_hapi_poverty_rate"
      p_coded: True
    headers:
      - location_code
      - has_hrp
      - in_gho
      - provider_admin1_name
      - admin1_code
      - admin1_name
      - admin_level
      - mpi
      - headcount_ratio
      - intensity_of_deprivation
      - vulnerable_to_poverty
      - in_severe_poverty
      - reference_period_start
      - reference_period_end

  population:
    make_global_dataset: False
    title: "HDX HAPI - Geography & Infrastructure: Baseline Population"
    tags:
      - "baseline population"
    resource:
      name: "Geography & Infrastructure: Baseline Population"
      description: "Baseline Population data from HDX HAPI, please see [the documentation](https://hdx-hapi.readthedocs.io/en/latest/data_usage_guides/geography_and_infrastructure/#baseline-population) for more information"
      filename: "hdx_hapi_population"
      p_coded: True
    headers:
      - location_code
      - has_hrp
      - in_gho
      - provider_admin1_name
      - provider_admin2_name
      - admin1_code
      - admin1_name
      - admin2_code
      - admin2_name
      - admin_level
      - gender
      - age_range
      - min_age
      - max_age
      - population
      - reference_period_start
      - reference_period_end

  rainfall:
    make_global_dataset: False
    title: "HDX HAPI - Climate: Rainfall"
    tags:
      - "climate-weather"
    resource:
      name: "Climate: Rainfall"
      description: "Rainfall data from HDX HAPI, please see [the documentation](https://hdx-hapi.readthedocs.io/en/latest/data_usage_guides/climate/#rainfall) for more information"
      filename: "hdx_hapi_rainfall"
      p_coded: True
    headers:
      - location_code
      - has_hrp
      - in_gho
      - provider_admin1_name
      - provider_admin2_name
      - admin1_code
      - admin1_name
      - admin2_code
      - admin2_name
      - admin_level
      - provider_admin1_code
      - provider_admin2_code
      - aggregation_period
      - rainfall
      - rainfall_long_term_average
      - rainfall_anomaly_pct
      - number_pixels
      - version
      - reference_period_start
      - reference_period_end

  data_availability:
    make_global_dataset: True
    title: "HDX HAPI - Metadata: Data Availability"
    source_override: "[HDX HAPI](https://hapi.humdata.org/)"
    license_override: "[Creative Commons Attribution for Intergovernmental Organisations](http://creativecommons.org/licenses/by/3.0/igo/legalcode)"
    tags:
      - "indicators"
    resource:
      name: "Metadata: Data Availability"
      description: "Data Availability Data from HDX HAPI. Each row in this resource represents an administrative division for which data is available, by subcategory. Please see [the documentation](https://hdx-hapi.readthedocs.io/en/latest/data_usage_guides/metadata/#data-availability) for more information"
      filename: "hdx_hapi_data_availability"
      p_coded: True
    headers:
      - category
      - subcategory
      - location_code
      - admin1_code
      - admin1_name
      - admin2_code
      - admin2_name
      - admin_level
      - hapi_updated_date
