default_db_uri: "postgresql+psycopg://postgres:postgres@localhost:5432/hapirestore"

country_dataset_title: "HDX HAPI Data for {suffix}"
dataset_name: "hdx-hapi-{suffix}"
default_source: "HDX HAPI"
default_license: "cc-by-igo"
country_multiple_licenses: "Multiple licenses, please see individual resources for specific license information"

subcategories:
  idps:
    make_global_dataset: False
    title: "HDX HAPI - Affected People: Internally-Displaced Persons"
    tags:
      - "displacement"
      - "internally displaced persons-idp"
      - "migration"
    resource:
      name: "Affected People: Internally-Displaced Persons"
      description: "IDPs data from HDX HAPI, please see [the documentation](https://hdx-hapi.readthedocs.io/en/latest/data_usage_guides/affected_people/#internally-displaced-persons) for more information"
      filename: "hdx_hapi_idps"
    hxltags:
      location_code: "#country+code"
      has_hrp: "#meta+has_hrp"
      in_gho: "#meta+in_gho"
      provider_admin1_name: "#adm1+name+provider"
      provider_admin2_name: "#adm2+name+provider"
      admin1_code: "#adm1+code"
      admin1_name: "#adm1+name"
      admin2_code: "#adm2+code"
      admin2_name: "#adm2+name"
      admin_level: "#adm+level"
      operation: "#operation+name"
      assessment_type: "#assessment+type"
      population: "#affected+idps"
      reporting_round: "#round+code"
      reference_period_start: "#date+start"
      reference_period_end: "#date+end"

  refugees:
    make_global_dataset: False
    title: "HDX HAPI - Affected People: Refugees & Persons of Concern"
    tags:
      - "refugees"
    resource:
      name: "Affected People: Refugees & Persons of Concern"
      description: "Refugees and Persons of Concern data from HDX HAPI, please see [the documentation](https://hdx-hapi.readthedocs.io/en/latest/data_usage_guides/affected_people/#refugees-persons-of-concern) for more information"
      filename: "hdx_hapi_refugees"
    hxltags:
      origin_location_code: "#country+code+origin"
      origin_has_hrp: "#meta+has_hrp+origin"
      origin_in_gho: "#meta+in_gho+origin"
      asylum_location_code: "#country+code+asylum"
      asylum_has_hrp: "#meta+has_hrp+asylum"
      asylum_in_gho: "#meta+in_gho+asylum"
      population_group: "#population_group+code"
      gender: "#gender+code"
      age_range: "#age+range"
      min_age: "#age+min"
      max_age: "#age+max"
      population: "#population"
      reference_period_start: "#date+start"
      reference_period_end: "#date+end"

  returnees:
    make_global_dataset: False
    title: "HDX HAPI - Affected People: Returnees"
    tags:
      - "returnees"
    resource:
      name: "Affected People: Returnees"
      description: "Returnees data from HDX HAPI, please see [the documentation](https://hdx-hapi.readthedocs.io/en/latest/data_usage_guides/affected_people/#returnees) for more information"
      filename: "hdx_hapi_returnees"
    hxltags:
      origin_location_code: "#country+code+origin"
      origin_has_hrp: "#meta+has_hrp+origin"
      origin_in_gho: "#meta+in_gho+origin"
      asylum_location_code: "#country+code+asylum"
      asylum_has_hrp: "#meta+has_hrp+asylum"
      asylum_in_gho: "#meta+in_gho+asylum"
      population_group: "#population_group+code"
      gender: "#gender+code"
      age_range: "#age+range"
      min_age: "#age+min"
      max_age: "#age+max"
      population: "#population"
      reference_period_start: "#date+start"
      reference_period_end: "#date+end"

  humanitarian_needs:
    make_global_dataset: False
    title: "HDX HAPI - Affected People: Humanitarian Needs"
    tags:
      - "humanitarian needs overview-hno"
      - "people in need-pin"
    resource:
      name: "Affected People: Humanitarian Needs"
      description: "Humanitarian needs data from HDX HAPI, please see [the documentation](https://hdx-hapi.readthedocs.io/en/latest/data_usage_guides/affected_people/#humanitarian-needs) for more information"
      filename: "hdx_hapi_humanitarian_needs"
    hxltags:
      location_code: "#country+code"
      has_hrp: "#meta+has_hrp"
      in_gho: "#meta+in_gho"
      provider_admin1_name: "#adm1+name+provider"
      provider_admin2_name: "#adm2+name+provider"
      admin1_code: "#adm1+code"
      admin1_name: "#adm1+name"
      admin2_code: "#adm2+code"
      admin2_name: "#adm2+name"
      admin_level: "#adm+level"
      sector_code: "#sector+cluster+code"
      sector_name: "#sector+cluster+name"
      category: "#category"
      population_status: "#population+status"
      population: "#population"
      reference_period_start: "#date+start"
      reference_period_end: "#date+end"

  operational_presence:
    make_global_dataset: False
    title: "HDX HAPI - Coordination & Context: Operational Presence"
    tags:
      - "operational presence"
      - "who is doing what and where-3w-4w-5w"
    resource:
      name: "Coordination & Context: Operational Presence"
      description: "Operational Presence data from HDX HAPI, please see [the documentation](https://hdx-hapi.readthedocs.io/en/latest/data_usage_guides/coordination_and_context/#operational-presence) for more information"
      filename: "hdx_hapi_operational_presence"
    hxltags:
      location_code: "#country+code"
      has_hrp: "#meta+has_hrp"
      in_gho: "#meta+in_gho"
      provider_admin1_name: "#adm1+name+provider"
      provider_admin2_name: "#adm2+name+provider"
      admin1_code: "#adm1+code"
      admin1_name: "#adm1+name"
      admin2_code: "#adm2+code"
      admin2_name: "#adm2+name"
      admin_level: "#adm+level"
      org_acronym: "#org+acronym"
      org_name: "#org+name"
      org_type_description: "#org+type"
      sector_code: "#sector+cluster+code"
      sector_name: "#sector+cluster+name"
      reference_period_start: "#date+start"
      reference_period_end: "#date+end"

  funding:
    make_global_dataset: False
    title: "HDX HAPI - Coordination & Context: Funding"
    tags:
      - "funding"
    resource:
      name: "Coordination & Context: Funding"
      description: "Funding data from HDX HAPI, please see [the documentation](https://hdx-hapi.readthedocs.io/en/latest/data_usage_guides/coordination_and_context/#funding) for more information"
      filename: "hdx_hapi_funding"
    hxltags:
      location_code: "#country+code"
      has_hrp: "#meta+has_hrp"
      in_gho: "#meta+in_gho"
      appeal_code: "#activity+appeal+id+external"
      appeal_name: "#activity+appeal+name"
      appeal_type: "#activity+appeal+type+name"
      requirements_usd: "#value+funding+required+usd"
      funding_usd: "#value+funding+total+usd"
      funding_pct: "#value+funding+pct"
      reference_period_start: "#date+start"
      reference_period_end: "#date+end"

  conflict_event:
    make_global_dataset: False
    title: "HDX HAPI - Coordination & Context: Conflict Events"
    tags:
      - "conflict-violence"
    resource:
      name: "Coordination & Context: Conflict Events"
      description: "Conflict Event data from HDX HAPI, please see [the documentation](https://hdx-hapi.readthedocs.io/en/latest/data_usage_guides/coordination_and_context/#conflict-events) for more information"
      filename: "hdx_hapi_conflict_event"
    hxltags:
      location_code: "#country+code"
      has_hrp: "#meta+has_hrp"
      in_gho: "#meta+in_gho"
      provider_admin1_name: "#adm1+name+provider"
      provider_admin2_name: "#adm2+name+provider"
      admin1_code: "#adm1+code"
      admin1_name: "#adm1+name"
      admin2_code: "#adm2+code"
      admin2_name: "#adm2+name"
      admin_level: "#adm+level"
      event_type: "#event+type"
      events: "#indicator+event+num"
      fatalities: "#affected+killed"
      reference_period_start: "#date+start"
      reference_period_end: "#date+end"

  national_risk:
    make_global_dataset: True
    title: "HDX HAPI - Coordination & Context: National Risk"
    tags:
      - "hazards and risk"
    resource:
      name: "Coordination & Context: National Risk"
      description: "National Risk data from HDX HAPI, please see [the documentation](https://hdx-hapi.readthedocs.io/en/latest/data_usage_guides/coordination_and_context/#national-risk) for more information"
      filename: "hdx_hapi_national_risk"
    hxltags:
      location_code: "#country+code"
      has_hrp: "#meta+has_hrp"
      in_gho: "#meta+in_gho"
      risk_class: "#risk+class"
      global_rank: "#risk+rank"
      overall_risk: "#risk+total"
      hazard_exposure_risk: "#risk+hazard"
      vulnerability_risk: "#risk+vulnerability"
      coping_capacity_risk: "#risk+coping+capacity"
      meta_missing_indicators_pct: "#meta+missing+indicators+pct"
      meta_avg_recentness_years: "#meta+recentness+avg"
      reference_period_start: "#date+start"
      reference_period_end: "#date+end"

  food_security:
    make_global_dataset: False
    title: "HDX HAPI - Food Security, Nutrition & Poverty: Food Security"
    tags:
      - "food security"
    resource:
      name: "Food Security, Nutrition & Poverty: Food Security"
      description: "Food Security data from HDX HAPI, please see [the documentation](https://hdx-hapi.readthedocs.io/en/latest/data_usage_guides/food_security_nutrition_and_poverty/#food-security) for more information"
      filename: "hdx_hapi_food_security"
    hxltags:
      location_code: "#country+code"
      has_hrp: "#meta+has_hrp"
      in_gho: "#meta+in_gho"
      provider_admin1_name: "#adm1+name+provider"
      provider_admin2_name: "#adm2+name+provider"
      admin1_code: "#adm1+code"
      admin1_name: "#adm1+name"
      admin2_code: "#adm2+code"
      admin2_name: "#adm2+name"
      admin_level: "#adm+level"
      ipc_phase: "#severity+v_ipc"
      ipc_type: "#period+v_ipc"
      population_in_phase: "#affected+num"
      population_fraction_in_phase: "#affected+pct"
      reference_period_start: "#date+start"
      reference_period_end: "#date+end"

  food_price:
    make_global_dataset: False
    title: "HDX HAPI - Food Security, Nutrition & Poverty: Food Prices & Market Monitor"
    tags:
      - "economics"
      - "markets"
      - "food security"
    resource:
      name: "Food Security, Nutrition & Poverty: Food Prices & Market Monitor"
      description: "Food Prices & Market Monitor data from HDX HAPI, please see [the documentation](https://hdx-hapi.readthedocs.io/en/latest/data_usage_guides/food_security_nutrition_and_poverty/#food-prices-market-monitor) for more information"
      filename: "hdx_hapi_food_price"
    hxltags:
      location_code: "#country+code"
      has_hrp: "#meta+has_hrp"
      in_gho: "#meta+in_gho"
      provider_admin1_name: "#adm1+name+provider"
      provider_admin2_name: "#adm2+name+provider"
      admin1_code: "#adm1+code"
      admin1_name: "#adm1+name"
      admin2_code: "#adm2+code"
      admin2_name: "#adm2+name"
      admin_level: "#adm+level"
      market_name: "#loc+market+name"
      lat: "#geo+lat"
      lon: "#geo+lon"
      commodity_category: "#item+type"
      commodity_name: "#item+name"
      unit: "#item+unit"
      price_flag: "#item+price+flag"
      price_type: "#item+price+type"
      currency_code: "#currency"
      price: "#value"
      reference_period_start: "#date+start"
      reference_period_end: "#date+end"

  poverty_rate:
    make_global_dataset: False
    title: "HDX HAPI - Food Security, Nutrition & Poverty: Poverty Rate"
    tags:
      - "education"
      - "health"
      - "indicators"
      - "poverty"
    resource:
      name: "Food Security, Nutrition & Poverty: Poverty Rate"
      description: "Poverty Rate data from HDX HAPI, please see [the documentation](https://hdx-hapi.readthedocs.io/en/latest/data_usage_guides/food_security_nutrition_and_poverty/#poverty-rate) for more information"
      filename: "hdx_hapi_poverty_rate"
    hxltags:
      location_code: "#country+code"
      has_hrp: "#meta+has_hrp"
      in_gho: "#meta+in_gho"
      provider_admin1_name: "#adm1+name+provider"
      admin1_code: "#adm1+code"
      admin1_name: "#adm1+name"
      admin_level: "#adm+level"
      mpi: "#indicator+mpi"
      headcount_ratio: "#indicator+headcount_ratio"
      intensity_of_deprivation: "#indicator+intensity_of_deprivation"
      vulnerable_to_poverty: "#indicator+vulnerable_to_poverty"
      in_severe_poverty: "#indicator+in_severe_poverty"
      reference_period_start: "#date+start"
      reference_period_end: "#date+end"

  population:
    make_global_dataset: False
    title: "HDX HAPI - Geography & Infrastructure: Baseline Population"
    tags:
      - "baseline population"
    resource:
      name: "Geography & Infrastructure: Baseline Population"
      description: "Baseline Population data from HDX HAPI, please see [the documentation](https://hdx-hapi.readthedocs.io/en/latest/data_usage_guides/geography_and_infrastructure/#baseline-population) for more information"
      filename: "hdx_hapi_population"
    hxltags:
      location_code: "#country+code"
      has_hrp: "#meta+has_hrp"
      in_gho: "#meta+in_gho"
      provider_admin1_name: "#adm1+name+provider"
      provider_admin2_name: "#adm2+name+provider"
      admin1_code: "#adm1+code"
      admin1_name: "#adm1+name"
      admin2_code: "#adm2+code"
      admin2_name: "#adm2+name"
      admin_level: "#adm+level"
      gender: "#gender+code"
      age_range: "#age+range"
      min_age: "#age+min"
      max_age: "#age+max"
      population: "#population"
      reference_period_start: "#date+start"
      reference_period_end: "#date+end"

  rainfall:
    make_global_dataset: False
    title: "HDX HAPI - Climate: Rainfall"
    tags:
      - "climate-weather"
    resource:
      name: "Climate: Rainfall"
      description: "Rainfall data from HDX HAPI, please see [the documentation](https://hdx-hapi.readthedocs.io/en/latest/data_usage_guides/climate/#rainfall) for more information"
      filename: "hdx_hapi_rainfall"
    hxltags:
      location_code: "#country+code"
      has_hrp: "#meta+has_hrp"
      in_gho: "#meta+in_gho"
      provider_admin1_name: "#adm1+name+provider"
      provider_admin2_name: "#adm2+name+provider"
      admin1_code: "#adm1+code"
      admin1_name: "#adm1+name"
      admin2_code: "#adm2+code"
      admin2_name: "#adm2+name"
      admin_level: "#adm+level"
      provider_admin1_code: "#adm1+code+provider"
      provider_admin2_code: "#adm2+code+provider"
      aggregation_period: "#aggregation+period"
      rainfall: "#rainfall"
      rainfall_long_term_average: "#rainfall+lta"
      rainfall_anomaly_pct: "#rainfall+anomaly+pct"
      number_pixels: "#meta+pixels+num"
      version: "#meta+version"
      reference_period_start: "#date+start"
      reference_period_end: "#date+end"

  data_availability:
    make_global_dataset: True
    title: "HDX HAPI - Metadata: Data Availability"
    source_override: "[HDX HAPI](https://hapi.humdata.org/)"
    license_override: "[Creative Commons Attribution for Intergovernmental Organisations](http://creativecommons.org/licenses/by/3.0/igo/legalcode)"
    tags: []
    resource:
      name: "Metadata: Data Availability"
      description: "Data Availability Data from HDX HAPI. Each row in this resource represents an administrative division for which data is available, by subcategory. Please see [the documentation](https://hdx-hapi.readthedocs.io/en/latest/data_usage_guides/metadata/#data-availability) for more information"
      filename: "hdx_hapi_data_availability"
    hxltags:
      category: "#category"
      subcategory: "#subcategory"
      location_code: "#country+code"
      admin1_code: "#adm1+code"
      admin1_name: "#adm1+name"
      admin2_code: "#adm2+code"
      admin2_name: "#adm2+name"
      admin_level: "#adm+level"
      hapi_updated_date: "#date+updated"
