# This workflow will install Python dependencies and run the script

name: Run script

on:
  workflow_dispatch: # add run button in github
  schedule:
    - cron: "15 8 * * *"


jobs:
  run:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: hapirestore
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
          --name postgres-container

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.x
      uses: actions/setup-python@v5
      with:
        python-version: "3.x"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install .
    - name: Run script
      env:
        HDX_SITE: ${{ vars.HDX_SITE }}
        HDX_KEY: ${{ secrets.HDX_BOT_SCRAPERS_API_TOKEN }}
        PREPREFIX: ${{ vars.HDX_USER_AGENT_PREPREFIX }}
        USER_AGENT: ${{ vars.USER_AGENT }}
      run: |
        python -m hdx.scraper.hapi --restore_url=https://github.com/OCHA-DAP/hapi-pipelines/raw/refs/heads/db-export/database/hapi_db.pg_restore.xz -db "postgresql+psycopg://postgres:postgres@localhost:5432/hapirestore"
    - name: Send mail
      if: failure()
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: ${{secrets.HDX_PIPELINE_EMAIL_SERVER}}
        server_port: ${{secrets.HDX_PIPELINE_EMAIL_PORT}}
        username: ${{secrets.HDX_PIPELINE_EMAIL_USERNAME}}
        password: ${{secrets.HDX_PIPELINE_EMAIL_PASSWORD}}
        subject: "FAILED: ${{github.repository}} run job"
        body: GitHub Actions run job for ${{github.repository}} failed!
        to: ${{vars.HDX_PIPELINE_EMAIL_LIST}}
        from: ${{secrets.HDX_PIPELINE_EMAIL_FROM}}
        content_type: text/html
